---
:global:
  supported_oss:
    jantman-archlinux_workstation:           [linux]
    jantman-archlinux_macbookretina:         [linux]
    jantman-workstation_bootstrap:           [linux]
  module_repos:
    jantman-archlinux_workstation:   puppet-archlinux-workstation
    jantman-archlinux_macbookretina: puppet-archlinux-macbookretina
    jantman-workstation_bootstrap:   workstation-bootstrap
  module_names:
    jantman-archlinux_workstation:   archlinux_workstation
    jantman-archlinux_macbookretina: archlinux_macbookretina
    jantman-workstation_bootstrap:   workstation_bootstrap

.gitattributes:
  include:
    '*.rb': 'eol=lf'
    '*.erb': 'eol=lf'
    '*.pp': 'eol=lf'
    '*.sh': 'eol=lf'
.travis.yml:
  script: "\"bundle exec rake release_checks_nonparallel\""
  docker_sets:
  - set: default
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
    rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=foss BEAKER_debug=true BEAKER_set=@@SET@@
    script: bundle exec rake beaker
  includes:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
    bundler_args: --without system_tests
    script:
      - "bundle exec rake release_checks_nonparallel"
      - "bundle exec rake clean"
      - "bundle exec rake build"
      - "bundle exec rake docs"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
Gemfile:
  required:
    ':development':
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-default-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-default-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: 'puppet-module-posix-dev-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-dev-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
        version: '0.0.7'
      # json_pure 2.0.2 added a requirement on ruby >= 2. We pin to json_pure <= 2.0.1
      # if using ruby 1.x
      - gem: json_pure
        version: '<= 2.0.1'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
      - gem: fast_gettext
        version: '1.1.0'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.1.0')"
      - gem: fast_gettext
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.1.0')"
      - gem: puppet-strings
    ':system_tests':
      - gem: beaker-docker
        version: '>= 0.3.0'
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: beaker
        version: '>= 3'
        from_env: 'BEAKER_VERSION'
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
      - gem: beaker-abs
        from_env: 'BEAKER_ABS_VERSION'
        version: '~> 0.1'
      - gem: puppet-blacksmith
        version: '>= 4.1.1'
      - gem: vandamme
      - gem: octokit
        version: '~> 4.0'
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests"
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 5.0'
      RUBY_VER: 24
    - PUPPET_GEM_VERSION: '~> 5.0'
      RUBY_VER: 24-x64
    # Oldest supported version
    - PUPPET_GEM_VERSION: '4.7.1'
      RUBY_VER: 21-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"

LICENSE:
  license_type: 'GPL-3.0' # Available options 'puppetpe' and 'apache2' (default is apache2)

MAINTAINERS.md:
  maintainers:
    - "Jason Antman `jason |at| jasonantman |dot| com`"

# Apache 2 NOTICE file generation.  Please mark unmanaged:true if using puppetpe license type
NOTICE:
  copyright_holders:
    - name: 'Jason Antman'
      begin: 'latest'
    # - name: '<name of holder>' (required)
    #   begin: <year or 'latest'> (optional) (latest is the year when modsync is run)
    #   end:   <year or 'latest'> (optional) (latest is the year when modsync is run)

Rakefile:
  default_disabled_lint_checks:
  - 'relative'

CONTRIBUTING.md:

spec/spec.opts:
  delete: true

locales/config.yaml:
  copyright_holder: 'Jason Antman'
  comments_tag: 'TRANSLATOR'
  bugs_address: 'jason@jasonantman.com'
  default_locale: 'en'
  source_files:
    - './lib/**/*.rb'

spec/spec_helper.rb:
spec/acceptance/nodesets/default.yml:
